name: Deploy Development to Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Build Docker Image
        run: docker build -t registry.heroku.com/heroku-deploy/web .

      - name: Login to the Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Push Docker Image to Image Hub
        run: heroku container:push web -a heroku-deploy

      - name: Release Docker Image to Heroku
        run: heroku container:release web -a heroku-deploy
